# -*- coding: utf-8 -*-
"""Spam email Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ddLKbcddkEI9tA8kRH8XawBlArYRHRv
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

df = pd.read_csv("SMSSpamCollection", sep="\t", header=None, names=["label", "message"])

print(df.head())  # Show first few rows

X = df['message']       # Features (text)
y = df['label']         # Target (spam/ham)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)
print("Accuracy:", accuracy_score(y_test, y_pred))

sample = ["Congratulations! You have won a free ticket to Bahamas. Claim now!"]
sample_vec = vectorizer.transform(sample)
print("Prediction:", model.predict(sample_vec)[0])